FROM golang:latest

WORKDIR /go/src/github.com/sqrthree/progressbar201X

RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && chmod +x /usr/local/bin/dep

EXPOSE 3000

CMD ["go", "run", "cmd/progressbar201X/main.go"]
